src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 */
class Property
{
    const HEAT=[
        0 => "Electrique",
        1 => "Gaz"
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 10,
     *      max = 400,
     *      notInRangeMessage = "You must be between {{ min }}cm and {{ max }}cm tall to enter",
     * )
     */
    private $surface;

    /**
     * @ORM\Column(type="datetime")
     *
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean",options={"default":false})
     */
    private $sold=false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="property", orphanRemoval=true
     *  ,cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *  @Assert\Image(mimeTypes="image/jpeg" )})
     *
     * @var Mixed_
     */
    private $pictureFiles;

    /**
     * @ORM\Column(type="float" ,scale=4, precision= 6)
     *
     */
    private $lat;

    /**
     * @ORM\Column(type="float" ,scale=4, precision= 7)
     */
    private $lng;

    /**
     * Undocumented function
     */
    public function __construct()
    {
        $this->create_at=new \DateTime();
        $this->options = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }


    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, "", " ");
    }

    public function getSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title); // hello-world
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }
    public function __toString()
    {
        return $this->title;
    }

   

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProperty($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getProperty() === $this) {
                $picture->setProperty(null);
            }
        }

        return $this;
    }

    /**
     * Get the value of pictureFiles
     *
     * @return  Mixed_
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTime();
        }
    }

    /**
     * Set the value of pictureFiles
     *
     * @param  Mixed_  $pictureFiles
     *
     * @return  self
     */
    public function setPictureFiles(Mixed_ $pictureFiles)
    {
        $this->pictureFiles = $pictureFiles;

        return $this;
    }

    /**
     * Get the value of lat
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Set the value of lat
     *
     * @return  self
     */
    public function setLat($lat)
    {
        $this->lat = $lat;

        return $this;
    }

    /**
     * Get the value of lng
     */
    public function getLng()
    {
        return $this->lng;
    }

    /**
     * Set the value of lng
     *
     * @return  self
     */
    public function setLng($lng)
    {
        $this->lng = $lng;

        return $this;
    }
}

src/Form/PropertyType.php
<?php
            
namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true,
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('sold')
            ->add('postal_code')
            ->add('lat', HiddenType::class)
            ->add('lng', HiddenType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation domain' => 'forms'
        ]);
    }
    private function getChoices()
    {
        $choices=Property::HEAT;
        $output=[];
        foreach ($choices as $key => $value) {
            $output[$value]=$key;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;

use App\Form\ContactType;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Notification\ContactNotification;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repo;

    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repo, EntityManagerInterface $em)
    {
        $this->repo=$repo;
        $this->em=$em;
    }
    /**
     * @Route("/biens", name="property.index")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search=new PropertySearch();
        $form=$this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties=$paginator->paginate(
            $this->repo->findAllVisibleQuery($search),
        /* query NOT result */
        $request->query->getInt('page', 1), /*page number*/
        12 /*limit per page*/
        );
        
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

   

    /**
    * @Route("/biens/{slug}-{id}", name="property.show",requirements={"slug":"[a-z0-9\-]*"})
    */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notif): Response
    {
        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }

        $contact=new Contact();
        $contact->setProperty($property);
        $form=$this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $notif->notify($contact);
           
            $this->addFlash('success', "Votre email a bien été envoyé");
         
            return $this->redirectToRoute('property.show', [
               'id' => $property->getId(),
               'slug' => $property->getSlug()
            ]);
        }

        
        return $this->render('property/show.html.twig', [
            'current_menu' => 'properties',
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos biens !
{% endblock %}


{% block body %}
	.<div class="jumbotron">
		.<div class="container">
			{{form_start(form)}}
			<div class="form-row align-items-end">
				<div class="col">
					{{form_row(form.minSurface)}}
				</div>
				<div class="col">
					{{form_row(form.maxPrice)}}
				</div>
				<div class="col">
					{{form_row(form.options)}}
				</div>

				<div class="col">
					{{form_row(form.address, {id: 'searchAdress'})}}
				</div>

				<div class="col">
					{{form_row(form.distance)}}
				</div>


				<div class="col">
					<div class="form-group">
						<button class="btn btn-primary">Recherche</button>

					</div>
				</div>


			</div>
			{{form_end(form)}}

		</div>
	</div>

	<div class="container mt-4">
		<h1>Voir tous nos biens</h1>
		<div class="row">
			{% for property in properties %}
				<div class="col-md-4">
					{% include "property/property.html.twig" %}

				</div>
			{% endfor %}

		</div>
		<div class="pagination">

			{{ knp_pagination_render(properties) }}
		</div>

	</div>
{% endblock %}

templates/property/property.html.twig
<div class="card mb-4">

	<img src="/images/properties/empty.jpg" alt="card-img-top" style="width:100%;height:auto;">


	<div class="card-body">
		<h5 class="card-title">
			<a href="{{path('property.show',{slug:property.slug,id:property.id})}}">
				{{property.title}}
			</a>
		</h5>
		<p class="card-text">{{property.description | nl2br }}</p>
		<p class="card-text">{{property.surface}}
			m² -
			{{property.city}}({{property.postalCode}})</p>

		<div class="text-primary" style="font-size:2 rem;font-weight:bold;">
			{{property.formattedPrice}}
			FCFA
		</div>


	</div>
</div>

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<div class="jumbotron">
		<div class="container">
			{% for message in app.flashes('success') %}

				<div class="alert alert-success">
					{{message}}
				</div>

			{% endfor %}

			{% if not form.vars.valid %}

				<div class="alert alert-danger">
					Erreur sur le formulaire !!
				</div>


			{% endif %}


			<div class="row">

				<div class="col-md-8">
					<div data-slider>
						{% if property.pictures is empty %}
							<img src="/images/properties/empty.jpg" alt="card-img-top" style="width:75%;height:auto;">


						{% else %}
							{% for picture in property.pictures %}

								<img src="{{vich_uploader_asset(picture,'imageFile')}}" alt="card-img-top" style="width:75%;height:auto;">
							{% endfor %}

						{% endif %}

					</div>

				</div>

				<div class="col-md-4">

					<h1>{{property.title}}</h1>
					<h2>{{property.rooms}}
						pièces -
						{{property.surface}}
						m²</h2>
					<div class="text-primary" style="font-weight:bold;font-size:4 rem;">{{property.getFormattedPrice}}
						FCFA</div>

					<a class="btn btn-primary" href="#" id="contactButton" {% if form.vars.submitted %} style="display:none;" {% endif %}>Contactez l'agence</a>

					<div id="contactForm" class="mt-4" {% if not form.vars.submitted %} style="display:none;" {% endif %}>


						{{form_start(form)}}
						<div class="row">


							<div class="col">
								{{form_row(form.firstname)}}
							</div>
							<div class="col">
								{{form_row(form.lastname)}}
							</div>
						</div>
						<div class="row">
							<div class="col">
								{{form_row(form.phone)}}
							</div>
							<div class="col">
								{{form_row(form.email)}}
							</div>
						</div>
						{{form_rest(form)}}
						*<div class="form-group">
							<button class="btn btn-primary">Envoyer</button>
						</div>

						{{form_end(form)}}

					</div>

				</div>
			</div>

		</div>
	</div>

	<div class="container mt-4">
		<p>{{property.description|nl2br}}</p>

		<div class="row">
			<div class="col-md-8">
				<table class="table table-striped">

					<tr>
						<td>Surface habitable</td>
						<td>{{property.surface}}
							m²</td>
					</tr>
					<tr>
						<td>Pièces</td>
						<td>{{property.rooms}}</td>
					</tr>
					<tr>
						<td>Chambres</td>
						<td>{{property.bedrooms}}</td>
					</tr>
					<tr>
						<td>Etage</td>
						<td>{{property.floor}}</td>
					</tr>
					<tr>
						<td>Chauffage</td>
						<td>{{property.heatType}}</td>
					</tr>


				</table>
			</div>


			<div class="col-md-4">
				<h2>Specificités</h2>
				<ul class="list-group">
					{% for option in property.options %}
						<li class="list-group-item">
							{{option.name}}
						</li>

					{% endfor %}

				</ul>

			</div>

		</div>
		<div id="map" style="width:100%; height:400px;" data-lat="{{property.lat}}" data-lng="{{property.lng}}"></div>


	</div>


{% endblock %}

{% block title %}{% endblock %}